import React from 'react';
import Head from 'next/head';
import { signOut } from 'next-auth/react';

import Header from '../components/Header';

const index = () => {
  return (
    <div>
      <Head>
        <title>LinkedIn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />

      <main></main>
    </div>
  );
};

export default index;
